CHANNEL_NAME_PIANO = 'piano'
CHANNEL_NAME_ACOUSTIC_GUITAR = 'acoustic_guitar'
CHANNEL_NAME_ELECTRIC_GUITAR_CLEAN = 'electric_guitar_clean'
CHANNEL_NAME_FINGER_STYLE_BASS = 'finger_style_bass'
CHANNEL_NAME_ENSEMBLE_STRING_1 = 'ensemble_string_1'
CHANNEL_NAME_ENSEMBLE_STRING_2 = 'ensemble_string_2'
CHANNEL_NAME_CHURCH_ORGAN = 'church_organ'
CHANNEL_NAME_ELECTRIC_PIANO = 'electric_piano'
CHANNEL_NAME_DRUM_KIT = 'drum_kit'

# define some custom channel mapping
channel_map = {
    CHANNEL_NAME_PIANO: 0,
    CHANNEL_NAME_ACOUSTIC_GUITAR: 1,
    CHANNEL_NAME_ELECTRIC_GUITAR_CLEAN: 2,
    CHANNEL_NAME_FINGER_STYLE_BASS: 3,
    CHANNEL_NAME_ENSEMBLE_STRING_1: 4,
    CHANNEL_NAME_ENSEMBLE_STRING_2: 5,
    CHANNEL_NAME_CHURCH_ORGAN: 6,
    CHANNEL_NAME_ELECTRIC_PIANO: 7,
    # drum should always be channel 9 and we do not need to change its program
    CHANNEL_NAME_DRUM_KIT: 9,
}
reversed_channel_map = {v: k for k, v in channel_map.items()}

CENTRAL_PANNING = 64
channel_panning_map = {
    CHANNEL_NAME_PIANO: 64,
    CHANNEL_NAME_ACOUSTIC_GUITAR: 36,
    CHANNEL_NAME_ELECTRIC_GUITAR_CLEAN: 36,
    CHANNEL_NAME_FINGER_STYLE_BASS: 64,
    CHANNEL_NAME_ENSEMBLE_STRING_1: 108,
    CHANNEL_NAME_ENSEMBLE_STRING_2: 12,
    CHANNEL_NAME_CHURCH_ORGAN: 64,
    CHANNEL_NAME_ELECTRIC_PIANO: 108,
    CHANNEL_NAME_DRUM_KIT: 64,
}

# a bridge that tell which channel should use what instrument
channel_program_map = {
    CHANNEL_NAME_PIANO: 'Acoustic Grand Piano',
    CHANNEL_NAME_ACOUSTIC_GUITAR: 'Acoustic Guitar (steel)',
    CHANNEL_NAME_ELECTRIC_GUITAR_CLEAN: 'Electric Guitar (clean)',
    CHANNEL_NAME_FINGER_STYLE_BASS: 'Electric Bass (finger)',
    CHANNEL_NAME_ENSEMBLE_STRING_1: 'String Ensemble 1',
    CHANNEL_NAME_ENSEMBLE_STRING_2: 'String Ensemble 2',
    CHANNEL_NAME_CHURCH_ORGAN: 'Church Organ',
    CHANNEL_NAME_ELECTRIC_PIANO: 'Electric Piano 1',
    CHANNEL_NAME_DRUM_KIT: 'Steel Drums',
}


def get_channel_program_int(channel: int):
    return program_map[channel_program_map[reversed_channel_map[channel]]]


# actual programming start with 0
program_map = {
    'Acoustic Grand Piano': 1,
    'Bright Acoustic Piano': 2,
    'Electric Grand Piano': 3,
    'Honky-tonk Piano': 4,
    'Electric Piano 1': 5,
    'Electric Piano 2': 6,
    'Harpsichord': 7,
    'Clavi': 8,
    'Celesta': 9,
    'Glockenspiel': 10,
    'Music Box': 11,
    'Vibraphone': 12,
    'Marimba': 13,
    'Xylophone': 14,
    'Tubular Bells': 15,
    'Dulcimer': 16,
    'Drawbar Organ': 17,
    'Percussive Organ': 18,
    'Rock Organ': 19,
    'Church Organ': 20,
    'Reed Organ': 21,
    'Accordion': 22,
    'Harmonica': 23,
    'Tango Accordion': 24,
    'Acoustic Guitar (nylon)': 25,
    'Acoustic Guitar (steel)': 26,
    'Electric Guitar (jazz)': 27,
    'Electric Guitar (clean)': 28,
    'Electric Guitar (muted)': 29,
    'Overdriven Guitar': 30,
    'Distortion Guitar': 31,
    'Guitar harmonics': 32,
    'Acoustic Bass': 33,
    'Electric Bass (finger)': 34,
    'Electric Bass (pick)': 35,
    'Fretless Bass': 36,
    'Slap Bass 1': 37,
    'Slap Bass 2': 38,
    'Synth Bass 1': 39,
    'Synth Bass 2': 40,
    'Violin': 41,
    'Viola': 42,
    'Cello': 43,
    'Contrabass': 44,
    'Tremolo Strings': 45,
    'Pizzicato Strings': 46,
    'Orchestral Harp': 47,
    'Timpani': 48,
    'String Ensemble 1': 49,
    'String Ensemble 2': 50,
    'SynthStrings 1': 51,
    'SynthStrings 2': 52,
    'Choir Aahs': 53,
    'Voice Oohs': 54,
    'Synth Voice': 55,
    'Orchestra Hit': 56,
    'Trumpet': 57,
    'Trombone': 58,
    'Tuba': 59,
    'Muted Trumpet': 60,
    'French Horn': 61,
    'Brass Section': 62,
    'SynthBrass 1': 63,
    'SynthBrass 2': 64,
    'Soprano Sax': 65,
    'Alto Sax': 66,
    'Tenor Sax': 67,
    'Baritone Sax': 68,
    'Oboe': 69,
    'English Horn': 70,
    'Bassoon': 71,
    'Clarinet': 72,
    'Piccolo': 73,
    'Flute': 74,
    'Recorder': 75,
    'Pan Flute': 76,
    'Blown Bottle': 77,
    'Shakuhachi': 78,
    'Whistle': 79,
    'Ocarina': 80,
    'Lead 1 (square)': 81,
    'Lead 2 (sawtooth)': 82,
    'Lead 3 (calliope)': 83,
    'Lead 4 (chiff)': 84,
    'Lead 5 (charang)': 85,
    'Lead 6 (voice)': 86,
    'Lead 7 (fifths)': 87,
    'Lead 8 (bass + lead)': 88,
    'Pad 1 (new age)': 89,
    'Pad 2 (warm)': 90,
    'Pad 3 (polysynth)': 91,
    'Pad 4 (choir)': 92,
    'Pad 5 (bowed)': 93,
    'Pad 6 (metallic)': 94,
    'Pad 7 (halo)': 95,
    'Pad 8 (sweep)': 96,
    'FX 1 (rain)': 97,
    'FX 2 (soundtrack)': 98,
    'FX 3 (crystal)': 99,
    'FX 4 (atmosphere)': 100,
    'FX 5 (brightness)': 101,
    'FX 6 (goblins)': 102,
    'FX 7 (echoes)': 103,
    'FX 8 (sci-fi)': 104,
    'Sitar': 105,
    'Banjo': 106,
    'Shamisen': 107,
    'Koto': 108,
    'Kalimba': 109,
    'Bag pipe': 110,
    'Fiddle': 111,
    'Shanai': 112,
    'Tinkle Bell': 113,
    'Agogo': 114,
    'Steel Drums': 115,
    'Woodblock': 116,
    'Taiko Drum': 117,
    'Melodic Tom': 118,
    'Synth Drum': 119,
    'Reverse Cymbal': 120,
    'Guitar Fret Noise': 121,
    'Breath Noise': 122,
    'Seashore': 123,
    'Bird Tweet': 124,
    'Telephone Ring': 125,
    'Helicopter': 126,
    'Applause': 127,
    'Gunshot': 128,
}
program_map = {k: v - 1 for k, v in program_map.items()}
